[shaft_element.0]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 0
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.1]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 1
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.2]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 2
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.3]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 3
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.4]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 4
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.5]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 5
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.6]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 6
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.7]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 7
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.8]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 8
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.9]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 9
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.10]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 10
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.11]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 11
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.12]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 12
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.13]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 13
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.14]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 14
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.15]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 15
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.16]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 16
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.17]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 17
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.18]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 18
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.19]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 19
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.20]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 20
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.21]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 21
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.22]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 22
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.23]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 23
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.24]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 24
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.25]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 25
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.26]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 26
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.27]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 27
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.28]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 28
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.29]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 29
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.30]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 30
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.31]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 31
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.32]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 32
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.33]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 33
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.34]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 34
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.35]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 35
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.36]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 36
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.37]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 37
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.38]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 38
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.39]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 39
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.40]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 40
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.41]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 41
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.42]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 42
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.43]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 43
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.44]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 44
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.45]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 45
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.46]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 46
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"

[shaft_element.47]
L = 0.03125
i_d = 0.0
o_d = 0.05
material = "Steel"
n = 47
axial_force = 0
torque = 0
shear_effects = true
rotary_inertia = true
gyroscopic = true
shear_method_calc = "cowper"
